---
title: "Group_8_Formal_Analysis"
echo: false
format: html
editor: visual
self-contained: true
---

```{r}


data <- read.csv("DAProject9.csv")
library(dplyr)
data <- data %>%
  mutate(Obese = ifelse(BMIgroup == "Obese", 1, 0))
library(ggplot2)
library(tidyverse)
library(tidymodels)
library(gt)
library(MASS)
library(patchwork)
library(moderndive)
```

```{r}
#fitting a logistic regression model for each explanatory variable 


#age
modelage <- glm(Obese ~ AgeGroup,
                data = data, family = binomial)
summary(modelage)

#sex
modelsex <- glm(Obese ~ Sex,
                data = data, family = binomial)
summary(modelsex)

#socio-economic status
modelecon <- glm(Obese ~ Employment,
                 data = data, family = binomial)
summary(modelecon)

```

```{r}

```

The baseline category for the binary response is not obese and the baseline category for age is 16-24. This means that estimates from the logistic regression model are for a change on the log-odds scale for being obese in comparison to the response baseline of not obese and for all other age groups in comparison to age group 16-24.
