---
title: "Group_8_Exploratory_Analysis"
format: html
editor: visual
echo: false
self-contained: true
editor_options: 
  chunk_output_type: inline
---

```{r}
#Creating the binary variable for obesity
data <- read.csv('DAProject9.csv')
library(dplyr)
data <- data %>%
  mutate(Obese = ifelse(BMIgroup == "Obese", 1, 0))

```

```{r}
#Attempting to create the time series plot
data_2008 <- subset(data, Year == '2008' & Obese == 1)
data_2009 <- subset(data, Year == '2009'& Obese == 1)
data_2010 <- subset(data, Year == '2010'& Obese == 1)
data_2011 <- subset(data, Year == '2011'& Obese == 1)
data_2012 <- subset(data, Year == '2012'& Obese == 1)


year <- c(2008, 2009, 2010, 2011, 2012)
no_obese <- c(1448, 1647, 1666, 1620, 1088)

year_obese <- cbind(year, no_obese)
  year_obese <- as.data.frame(year_obese)

as.factor(year_obese$year)

library(ggplot2)
ggplot(year_obese, aes(x = year, y = no_obese)) +
  geom_line() +
  geom_point() +
  labs(title = "Time Series Plot of Obese Observations Over Time",
       x = "Year",
       y = "Number of Observations Obese")
```

```{r}
#Summary table
summary_by_year <- data %>%
  group_by(Year) %>%
  summarize(Count_Obese = sum(Obese))
summary_by_year

#Histogram of year v counts
ggplot(data = summary_by_year, aes(x = Year, y = Count_Obese)) +
  geom_col(fill='blue') +
  labs(x = "Year", y = "Obese Count",
       title = "Histogram of Obese Count by Year")
```
